server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848 #nacos地址
    gateway:
      routes:
        - id: user-service # 路由标示,必须唯一
          uri: lb://userservice # 路由的目标地址
          predicates: # 路由断言,判断请求是否符合规则
            - Path=/user/** # 路径断言,判断路劲是否以/user开头,是则true
#          filters:
#            - AddRequestHeader=Truth,patience is key in live # 网关过滤器,可以对请求进行一个处理,现在是对请求添加头的一个例子
        - id: order-service # 路由标示,必须唯一
          uri: lb://orderservice # 路由的目标地址
          predicates: # 路由断言,判断请求是否符合规则
            - Path=/order/** # 路径断言,判断路劲是否以/user开头,是则true
      default-filters:
        - AddRequestHeader=Truth,patience is key in live # 全局过滤器
      globalcors: #全局跨域处理
        add-to-simple-url-handler-mapping: true #解决options请求被拦截问题
        cors-configurations:
          '[/^^]':
            allowed-origins: # 允许那些网站可以跨域请求
              - "http://localhost:8090"
            allowed-methods:  #允许跨域ajax的请求方式
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "OPTIONS"
            allowedHeaders: "*" # 允许在请求中携带头信息
            allowCredentials: true # 是否允许携带cookie
            maxAge: # 这次跨域检测的有效期



